/**
 * DO NOT MODIFY. This file is autogenerated.
 */
import { useContext } from 'react';
import { getJBETHPaymentTerminal } from 'juice-sdk';

import { JuiceContext } from 'contexts/JuiceContext';

export function useJBETHPaymentTerminal() {
  const { provider } = useContext(JuiceContext);

  return getJBETHPaymentTerminal(provider);
}
