/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */
import { useContext } from 'react';
import { getJB3DayReconfigurationBufferBallot } from 'juice-sdk';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJB3DayReconfigurationBufferBallot() {
  const { provider } = useContext(JuiceContext);

  return getJB3DayReconfigurationBufferBallot(provider);
}
