/**
 * DO NOT MODIFY. This file is autogenerated.
 */
import { useContext } from 'react';
import { getJBDirectory } from 'juice-sdk';

import { JuiceContext } from 'contexts/JuiceContext';

export function useJBDirectory() {
  const { provider } = useContext(JuiceContext);

  return getJBDirectory(provider);
}
