/**
 * DO NOT MODIFY. This file is autogenerated.
 */
import { useContext } from 'react';
import { getJBProjects } from 'juice-sdk';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJBProjects() {
  const { provider } = useContext(JuiceContext);

  return getJBProjects(provider);
}
