/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */
import { useContext } from 'react';
import { getJBTokenStore } from 'juice-sdk';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJBTokenStore() {
  const { provider } = useContext(JuiceContext);

  return getJBTokenStore(provider);
}
