/**
 * DO NOT MODIFY. This file is autogenerated.
 */
import { useContext } from 'react';
import { getJBSingleTokenPaymentTerminalStore } from 'juice-sdk';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJBSingleTokenPaymentTerminalStore() {
  const { provider } = useContext(JuiceContext);

  return getJBSingleTokenPaymentTerminalStore(provider);
}
