/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */
import { useContext } from 'react';
import { getJBETHERC20ProjectPayerDeployer } from 'juice-sdk';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJBETHERC20ProjectPayerDeployer() {
  const { provider } = useContext(JuiceContext);

  return getJBETHERC20ProjectPayerDeployer(provider);
}
