/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */
import { useContext } from 'react';
import { getJBController } from 'juice-sdk';

import { JuiceContext } from 'contexts/JuiceContext';

export function useJBController() {
  const { provider } = useContext(JuiceContext);

  return getJBController(provider);
}
