/**
 * DO NOT MODIFY. This file is autogenerated.
 */
import { useContext } from 'react';
import { getJBSplitsStore } from 'juice-sdk';

import { JuiceContext } from 'contexts/JuiceContext';

export function useJBSplitsStore() {
  const { provider } = useContext(JuiceContext);

  return getJBSplitsStore(provider);
}
