/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 */
import { useContext } from 'react';
import { getJBETHERC20SplitsPayerDeployer } from 'juice-sdk';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJBETHERC20SplitsPayerDeployer() {
  const { provider } = useContext(JuiceContext);

  return getJBETHERC20SplitsPayerDeployer(provider);
}
