/**
 * DO NOT MODIFY. This file is autogenerated.
 */
import { useContext } from 'react';
import { getJB7DayReconfigurationBufferBallot } from 'juice-sdk';

import { JuiceContext } from '../../../contexts/JuiceContext';

export function useJB7DayReconfigurationBufferBallot() {
  const { provider } = useContext(JuiceContext);

  return getJB7DayReconfigurationBufferBallot(provider);
}
