/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface JBChainlinkV3PriceFeedInterface extends utils.Interface {
  functions: {
    "currentPrice(uint256)": FunctionFragment;
    "feed()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "currentPrice" | "feed"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "currentPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feed", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "currentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feed", data: BytesLike): Result;

  events: {};
}

export interface JBChainlinkV3PriceFeed extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: JBChainlinkV3PriceFeedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     *  Gets the current price from the feed, normalized to the specified number of decimals.
     * @param _decimals The number of decimals the returned fixed point price should include.
     */
    currentPrice(
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    /**
     *  The feed that prices are reported from.
     */
    feed(overrides?: CallOverrides): Promise<[string]>;
  };

  /**
   *  Gets the current price from the feed, normalized to the specified number of decimals.
   * @param _decimals The number of decimals the returned fixed point price should include.
   */
  currentPrice(
    _decimals: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   *  The feed that prices are reported from.
   */
  feed(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    /**
     *  Gets the current price from the feed, normalized to the specified number of decimals.
     * @param _decimals The number of decimals the returned fixed point price should include.
     */
    currentPrice(
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     *  The feed that prices are reported from.
     */
    feed(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    /**
     *  Gets the current price from the feed, normalized to the specified number of decimals.
     * @param _decimals The number of decimals the returned fixed point price should include.
     */
    currentPrice(
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     *  The feed that prices are reported from.
     */
    feed(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     *  Gets the current price from the feed, normalized to the specified number of decimals.
     * @param _decimals The number of decimals the returned fixed point price should include.
     */
    currentPrice(
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     *  The feed that prices are reported from.
     */
    feed(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
